
#include <iostream>
using namespace std;
#include "snippets.h"

int main(int argc, char const *argv[])
{
	start("EA");
	icon ea("ea.png");
	navbar n;
	dropdown games("games",20,"black"),about("about",20),support("support",20);
	dropdownitem game1("browse",20);
	dropdownitem game2("library",20);
	dropdownitem game3("shop on origin",20);
	dropdownitem game4("subscribe",20);
	games.setMarginleft(40);
	navlink subscribe("subscribe");
	games.addItem(game1);
	games.addItem(game2);
	games.addItem(game3);
	games.addItem(game4);
	dropdownitem about1("about Ea");
	dropdownitem about2("News");
	dropdownitem about3("competetive gaming");
	dropdownitem about4("studios");
	dropdownitem about5("careers");
	about.addItem(about1);
	about.addItem(about2);
	about.addItem(about3);
	about.addItem(about4);
	about.addItem(about5);
	about.setColor("black");
	dropdownitem support1("help");
	dropdownitem support2("forums");
	support.addItem(support1);
	support.addItem(support2);
	support.setColor("black");
	searchbar searchhere("search your game here");
	searchhere.setWidth(400);
	searchhere.setMarginleft(400);
	n.addItem(ea);
	n.addItem(games);
	n.addItem(about);
	n.addItem(support);
	n.addItem(subscribe);
	n.addItem(searchhere);
	n.generate();
	containerfluid backgroundcontainer;
	icon earoundicon("earoundicon.png");
	earoundicon.setSize(10);
	earoundicon.setMargin(85);
	row r1;
	r1.addItem(earoundicon);
	icon player1("player1.jpg",20);
	icon player2("player2.jpg",20);
	icon player3("player3.jpg",20);
	icon player4("player4.jpg",20);
	icon player5("player5.jpg",20);
	player1.setMargin(20);
	player2.setMargin(20);
	player3.setMargin(40);
	player4.setMargin(40);
	player5.setMargin(40);
	col c1;
	c1.addItem(player1);
	c1.addItem(player2);
	r1.addItem(c1);
	col c2;
	c2.addItem(player3);
	c2.addItem(player4);
	c2.addItem(player5);
	r1.addItem(c2);
	button discount("get discount $");
	discount.setBackgroundcolor("yellow");
	discount.setTextcolor("black");
	discount.setMargin(20);
	r1.addItem(discount);
	backgroundcontainer.addItem(r1);
	backgroundcontainer.setHeight(1300);
	backgroundcontainer.setBackgroundimage("background.jpg");
	backgroundcontainer.generate();
	containerfluid redbar("red");
	redbar.setHeight(80);
	row redbaritems;
	col subscribeitems;
	heading h1("the best way to play");
	h1.setMargin(20);
	h1.setColor("white");
	subscribeitems.addItem(h1);
	button subscribebutton("Subscribe");
	subscribebutton.setTextcolor("red");
	subscribebutton.setBackgroundcolor("white");
	subscribeitems.addItem(subscribebutton);
	redbaritems.addItem(subscribeitems);
	redbar.addItem(redbaritems);
	redbar.setPadding(20);
	redbar.generate();
	containerfluid mobilegames;
	mobilegames.setHeight(500);
	mobilegames.setBackgroundcolor("white");
	heading h2("mobile sports games");
	h2.setColor("black");
	h2.setMargin(30);
	row mgrow;
	mgrow.addItem(h2);
	col mgcol;
	icon mobilegame1("game1.jpg",20);
	icon mobilegame2("game2.jpg",20);
	icon mobilegame3("game3.jpg",20);
	mobilegame1.setMargin(20);
	mobilegame2.setMargin(20);
	mobilegame3.setMargin(20);
	mgcol.addItem(mobilegame1);
	mgcol.addItem(mobilegame2);
	mgcol.addItem(mobilegame3);
	mgrow.addItem(mgcol);
	mobilegames.addItem(mgrow);
	mobilegames.generate();
	containerfluid footer;
	footer.setHeight(100);
	footer.setBackgroundcolor("white");
	row footerrow;
	navlink n1("browse","grey",18),n2("about","grey",18),n3("support","grey",18),n4("shop here","grey",18);
	col footercol;
	footercol.addItem(ea);
	footercol.addItem(n1);
	footercol.addItem(n2);
	footercol.addItem(n3);
	footercol.addItem(n4);
	subscribebutton.setBackgroundcolor("red");
	subscribebutton.setTextcolor("white");
	footercol.addItem(subscribebutton);
	footerrow.addItem(footercol);
	h1.setText("2020 Electronic arts inc");
	h1.setFontsize(20);
	h1.setColor("grey");
	h1.setMargin(40);
	col footercol2;
	footercol2.addItem(h1);
	dropdown countries("country",20);
	dropdownitem country1("india");
	dropdownitem country2("united states");
	dropdownitem country3("united kingdom");
	countries.addItem(country1);
	countries.addItem(country2);
	countries.addItem(country3);
	countries.setColor("grey");
	footercol2.addItem(countries);
	footerrow.addItem(footercol2);
	inputfield report("report here");
	footerrow.addItem(report);
	footer.addItem(footerrow);

	footer.generate();
	deadend();
	return 0;
}
